spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/bmp
  sql:
    init:
      schema-locations: classpath:schema_mysql.sql
      # Supported database initialization modes.
      # always: Always initialize the database.
      # embedded: Only initialize an embedded database. Default value.
      # never: Only initialize an embedded database.
      mode: always
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

logging:
  level:
    com.bmp: debug

platform:
  mem:
    consumer-size: 2